# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RivneFish' do
pod 'Fabric'
pod 'Crashlytics'
end

target 'RivneFishTests' do

end

pod 'GoogleMaps', '~> 1.10.5'
pod 'SKPhotoBrowser', '~> 4.0'
# pod 'Google-Maps-iOS-Utils-QuadTree'
