# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RivneFish' do

end

target 'RivneFishTests' do

end

pod 'GoogleMaps'
# pod 'Google-Maps-iOS-Utils-QuadTree'
